In [1]:
# Set project paths.
from pathlib import Path
import os
import sys

def find_project_root():
    current = Path.cwd()

    for folder in [current] + list(current.parents):
        if (folder / "Data").exists() and (folder / "Notebooks").exists():
            return folder

    raise FileNotFoundError("Could not find project root. Make sure Data and Notebooks folders exist.")

project_folder = find_project_root()
notebook_folder = project_folder / "Notebooks"

os.chdir(project_folder)

print("Project folder:", project_folder)
print("Notebook folder:", notebook_folder)

Project folder: /Users/mac/Library/CloudStorage/OneDrive-UniversityofKeele/Dissertation/send-ev-project
Notebook folder: /Users/mac/Library/CloudStorage/OneDrive-UniversityofKeele/Dissertation/send-ev-project/Notebooks

In [2]:
# Import packages and helpers.
os.chdir(notebook_folder)

import import_ipynb
import pandas as pd
import plotly.express as px

from sklearn.metrics import r2_score, mean_absolute_error

from Data_Loader import DataLoader

os.chdir(notebook_folder)

from Training_Models import ConsumptionModel

os.chdir(project_folder)

print("Current folder:", os.getcwd())

Project folder: /Users/mac/Library/CloudStorage/OneDrive-UniversityofKeele/Dissertation/send-ev-project
Notebook folder: /Users/mac/Library/CloudStorage/OneDrive-UniversityofKeele/Dissertation/send-ev-project/Notebooks
                     air_temp  gti  surface_pressure  snow_depth  \
DateTime
2023-01-01 00:05:00         9    0             978.0         0.0
2023-01-01 00:10:00         9    0             978.1         0.0
2023-01-01 00:15:00         9    0             978.2         0.0
2023-01-01 00:20:00         9    0             978.2         0.0
2023-01-01 00:25:00         9    0             978.3         0.0

                     cloud_opacity  ghi  clearsky_gti  wind_speed_100m  \
DateTime
2023-01-01 00:05:00           33.8    0             0             11.0
2023-01-01 00:10:00           26.3    0             0             11.2
2023-01-01 00:15:00           27.8    0             0             11.4
2023-01-01 00:20:00           27.8    0             0             11.6
2023-01-01 00:25:00           43.6    0             0             11.8

                      weather_type
DateTime
2023-01-01 00:05:00  PARTLY CLOUDY
2023-01-01 00:10:00  PARTLY CLOUDY
2023-01-01 00:15:00  PARTLY CLOUDY
2023-01-01 00:20:00  PARTLY CLOUDY
2023-01-01 00:25:00  MOSTLY CLOUDY
                     power-con-ave  power-gen-wt-ave  power-gen-pv-ave
DateTime
2023-01-01 00:05:00       1317.487           573.029               0.0
2023-01-01 00:10:00       1319.056           612.280               0.0
2023-01-01 00:15:00       1338.842           652.990               0.0
2023-01-01 00:20:00       1329.313           813.526               0.0
2023-01-01 00:25:00       1338.366           643.773               0.0
                     expected
DateTime
2023-01-01 00:05:00       0.0
2023-01-01 00:10:00       0.0
2023-01-01 00:15:00       0.0
2023-01-01 00:20:00       0.0
2023-01-01 00:25:00       0.0
                     power-con-ave  power-gen-wt-ave  power-gen-pv-ave
DateTime
2022-03-01 00:00:00            0.0         20.708989               0.0
2022-03-01 00:05:00            0.0         31.507760               0.0
2022-03-01 00:10:00            0.0         24.946394               0.0
2022-03-01 00:15:00            0.0         24.961075               0.0
2022-03-01 00:20:00            0.0         26.129103               0.0
                     air_temp  gti  surface_pressure  snow_depth  \
DateTime
2022-01-01 00:05:00        12    0             996.2         0.0
2022-01-01 00:10:00        12    0             996.2         0.0
2022-01-01 00:15:00        12    0             996.2         0.0
2022-01-01 00:20:00        13    0             996.2         0.0
2022-01-01 00:25:00        13    0             996.2         0.0

                     cloud_opacity  ghi  clearsky_gti  wind_speed_100m  \
DateTime
2022-01-01 00:05:00           96.9    0             0              9.5
2022-01-01 00:10:00           96.9    0             0              9.6
2022-01-01 00:15:00           96.8    0             0              9.7
2022-01-01 00:20:00           96.8    0             0              9.7
2022-01-01 00:25:00           96.8    0             0              9.8

                    weather_type
DateTime
2022-01-01 00:05:00     OVERCAST
2022-01-01 00:10:00     OVERCAST
2022-01-01 00:15:00     OVERCAST
2022-01-01 00:20:00     OVERCAST
2022-01-01 00:25:00     OVERCAST
                     expected
DateTime
2022-01-01 00:05:00       0.0
2022-01-01 00:10:00       0.0
2022-01-01 00:15:00       0.0
2022-01-01 00:20:00       0.0
2022-01-01 00:25:00       0.0
Project folder: /Users/mac/Library/CloudStorage/OneDrive-UniversityofKeele/Dissertation/send-ev-project
Notebook folder: /Users/mac/Library/CloudStorage/OneDrive-UniversityofKeele/Dissertation/send-ev-project/Notebooks
Project folder: /Users/mac/Library/CloudStorage/OneDrive-UniversityofKeele/Dissertation/send-ev-project
Notebook folder: /Users/mac/Library/CloudStorage/OneDrive-UniversityofKeele/Dissertation/send-ev-project/Notebooks
                     air_temp  heating_demand  cooling_demand  hour  \
DateTime
2023-01-08 00:05:00         7              13               0     0
2023-01-08 00:10:00         7              13               0     0
2023-01-08 00:15:00         7              13               0     0
2023-01-08 00:20:00         7              13               0     0
2023-01-08 00:25:00         7              13               0     0

                     day_of_week  month  is_weekend  is_holiday  \
DateTime
2023-01-08 00:05:00            6      1           1           0
2023-01-08 00:10:00            6      1           1           0
2023-01-08 00:15:00            6      1           1           0
2023-01-08 00:20:00            6      1           1           0
2023-01-08 00:25:00            6      1           1           0

                     non_working_day  non_working_hour_interaction  ...  \
DateTime                                                            ...
2023-01-08 00:05:00                1                             0  ...
2023-01-08 00:10:00                1                             0  ...
2023-01-08 00:15:00                1                             0  ...
2023-01-08 00:20:00                1                             0  ...
2023-01-08 00:25:00                1                             0  ...

                     hour_sin  hour_cos   day_sin  day_cos  load_lag_1d  \
DateTime
2023-01-08 00:05:00  0.021815  0.999762 -0.781831  0.62349     1246.293
2023-01-08 00:10:00  0.043619  0.999048 -0.781831  0.62349     1233.700
2023-01-08 00:15:00  0.065403  0.997859 -0.781831  0.62349     1289.697
2023-01-08 00:20:00  0.087156  0.996195 -0.781831  0.62349     1250.529
2023-01-08 00:25:00  0.108867  0.994056 -0.781831  0.62349     1212.171

                     load_lag_7d  smart_lag  yesterday_daily_mean  \
DateTime
2023-01-08 00:05:00     1317.487   1317.487            1451.43967
2023-01-08 00:10:00     1319.056   1319.056            1451.43967
2023-01-08 00:15:00     1338.842   1338.842            1451.43967
2023-01-08 00:20:00     1329.313   1329.313            1451.43967
2023-01-08 00:25:00     1338.366   1338.366            1451.43967

                     yesterday_daily_max  rolling_7d_baseline
DateTime
2023-01-08 00:05:00             2203.093          1702.983728
2023-01-08 00:10:00             2203.093          1702.983728
2023-01-08 00:15:00             2203.093          1702.983728
2023-01-08 00:20:00             2203.093          1702.983728
2023-01-08 00:25:00             2203.093          1702.983728

[5 rows x 21 columns]
                     gti_target  cloud_opacity_target  snow_depth  month  \
DateTime
2023-01-15 00:05:00           0                   0.0         0.0      1
2023-01-15 00:10:00           0                   0.0         0.0      1
2023-01-15 00:15:00           0                   0.0         0.0      1
2023-01-15 00:20:00           0                   0.0         0.0      1
2023-01-15 00:25:00           0                   0.0         0.0      1

                     day_of_month  lag_1d  lag_2d  lag_3d  lag_7d  lag_14d  \
DateTime
2023-01-15 00:05:00            15     0.0     0.0     0.0     0.0      0.0
2023-01-15 00:10:00            15     0.0     0.0     0.0     0.0      0.0
2023-01-15 00:15:00            15     0.0     0.0     0.0     0.0      0.0
2023-01-15 00:20:00            15     0.0     0.0     0.0     0.0      0.0
2023-01-15 00:25:00            15     0.0     0.0     0.0     0.0      0.0

                     power_volatility_1d  power_trend_1d  gti_volatility_1d  \
DateTime
2023-01-15 00:05:00                  0.0             0.0                0.0
2023-01-15 00:10:00                  0.0             0.0                0.0
2023-01-15 00:15:00                  0.0             0.0                0.0
2023-01-15 00:20:00                  0.0             0.0                0.0
2023-01-15 00:25:00                  0.0             0.0                0.0

                     yesterday_peak  solar_potential  hour_sin  hour_cos
DateTime
2023-01-15 00:05:00         993.383              0.0       0.0       1.0
2023-01-15 00:10:00         993.383              0.0       0.0       1.0
2023-01-15 00:15:00         993.383              0.0       0.0       1.0
2023-01-15 00:20:00         993.383              0.0       0.0       1.0
2023-01-15 00:25:00         993.383              0.0       0.0       1.0
Consumption feature shape: (103103, 21)
PV feature shape: (101087, 17)
Current folder: /Users/mac/Library/CloudStorage/OneDrive-UniversityofKeele/Dissertation/send-ev-project
<class 'Training_Models.PVModel'>
<class 'Training_Models.ConsumptionModel'>
<class 'Training_Models.EvaluationMetrics'>
Current folder: /Users/mac/Library/CloudStorage/OneDrive-UniversityofKeele/Dissertation/send-ev-project

In [3]:
# Load data.
solcast, deop, expected = DataLoader.load_training_data()
deop_2022, solcast_2022, expected_2022 = DataLoader.load_testing_data()

print(deop.head())
print(solcast.head())
print(deop_2022.head())

                     power-con-ave  power-gen-wt-ave  power-gen-pv-ave
DateTime
2023-01-01 00:05:00       1317.487           573.029               0.0
2023-01-01 00:10:00       1319.056           612.280               0.0
2023-01-01 00:15:00       1338.842           652.990               0.0
2023-01-01 00:20:00       1329.313           813.526               0.0
2023-01-01 00:25:00       1338.366           643.773               0.0
                     air_temp  gti  surface_pressure  snow_depth  \
DateTime
2023-01-01 00:05:00         9    0             978.0         0.0
2023-01-01 00:10:00         9    0             978.1         0.0
2023-01-01 00:15:00         9    0             978.2         0.0
2023-01-01 00:20:00         9    0             978.2         0.0
2023-01-01 00:25:00         9    0             978.3         0.0

                     cloud_opacity  ghi  clearsky_gti  wind_speed_100m  \
DateTime
2023-01-01 00:05:00           33.8    0             0             11.0
2023-01-01 00:10:00           26.3    0             0             11.2
2023-01-01 00:15:00           27.8    0             0             11.4
2023-01-01 00:20:00           27.8    0             0             11.6
2023-01-01 00:25:00           43.6    0             0             11.8

                      weather_type
DateTime
2023-01-01 00:05:00  PARTLY CLOUDY
2023-01-01 00:10:00  PARTLY CLOUDY
2023-01-01 00:15:00  PARTLY CLOUDY
2023-01-01 00:20:00  PARTLY CLOUDY
2023-01-01 00:25:00  MOSTLY CLOUDY
                     power-con-ave  power-gen-wt-ave  power-gen-pv-ave
DateTime
2022-03-01 00:00:00            0.0         20.708989               0.0
2022-03-01 00:05:00            0.0         31.507760               0.0
2022-03-01 00:10:00            0.0         24.946394               0.0
2022-03-01 00:15:00            0.0         24.961075               0.0
2022-03-01 00:20:00            0.0         26.129103               0.0

In [4]:
# Choose consumption features.
con_features = [
    "air_temp", "heating_demand", "cooling_demand",
    "hour", "day_of_week", "month", "is_holiday",
    "non_working_day", "non_working_hour_interaction",
    "is_term_time",
    "hour_sin", "hour_cos", "day_sin", "day_cos",
    "smart_lag", "load_lag_7d",
    "yesterday_daily_mean", "yesterday_daily_max",
    "rolling_7d_baseline",
]

In [5]:
# Train consumption model.
con = ConsumptionModel(features=con_features)

con_preds, con_model = con.train_and_test(
    deop,
    solcast,
    deop_2022,
    solcast_2022,
    days_ahead=1,
)

Training new consumption model
5-Minute R2 Score: 0.8826 | MAE: 152.80 kW | MBE: -24.21 kW
Hourly R2 Score:   0.8965 | MAE: 140.92 kW
Daily R2 Score:    0.9315 | MAE: 92.71 kW

In [6]:
# Build results table.
consumption_results = pd.DataFrame({
    "actual": deop_2022.loc[con_preds.index, "power-con-ave"],
    "predicted": con_preds,
})

consumption_results.head()

                     actual  predicted
DateTime
2022-03-08 00:00:00     0.0        0.0
2022-03-08 00:05:00     0.0        0.0
2022-03-08 00:10:00     0.0        0.0
2022-03-08 00:15:00     0.0        0.0
2022-03-08 00:20:00     0.0        0.0

In [7]:
# Plot actual vs predicted.
hourly_results = consumption_results.resample("1h").mean()

fig = px.line(
    hourly_results,
    y=["actual", "predicted"],
    title="Consumption: Actual vs Predicted",
    labels={"value": "Power [kW]", "DateTime": "Time"},
)

fig.show()

In [8]:
# Calculate monthly scores.
monthly_scores = []

for month, group in consumption_results.groupby(consumption_results.index.month):
    r2 = r2_score(group["actual"], group["predicted"])
    mae = mean_absolute_error(group["actual"], group["predicted"])

    monthly_scores.append({
        "month": month,
        "r2": r2,
        "mae": mae,
    })

monthly_scores = pd.DataFrame(monthly_scores)
monthly_scores

   month        r2         mae
0      3  0.000000  111.156877
1      4  0.723292  250.884345
2      5  0.819100  149.718676
3      6  0.699602  173.667376
4      7  0.866111   98.273352
5      8  0.814993  133.016275
6      9  0.792440  146.714084
7     10  0.768677  166.393611
8     11  0.892501  122.338775
9     12  0.673523  169.132829

In [9]:
# Plot monthly scores.
fig = px.bar(
    monthly_scores,
    x="month",
    y="r2",
    title="Consumption Model Monthly R2 Score",
    labels={"month": "Month", "r2": "R2 Score"},
)

fig.show()

In [10]:
# Run forecast horizons.
con_predictions = {}

for i in range(1, 15):
    print("Running", i, "day forecast")

    preds, _ = con.train_and_test(
        deop,
        solcast,
        deop_2022,
        solcast_2022,
        days_ahead=i,
    )

    con_predictions[f"{i}-Day Forecast"] = preds

Running 1 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.8826 | MAE: 152.80 kW | MBE: -24.21 kW
Hourly R2 Score:   0.8965 | MAE: 140.92 kW
Daily R2 Score:    0.9315 | MAE: 92.71 kW
Running 2 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.8624 | MAE: 163.69 kW | MBE: -17.90 kW
Hourly R2 Score:   0.8762 | MAE: 152.52 kW
Daily R2 Score:    0.9050 | MAE: 106.97 kW
Running 3 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.8414 | MAE: 174.64 kW | MBE: -13.33 kW
Hourly R2 Score:   0.8551 | MAE: 163.91 kW
Daily R2 Score:    0.8752 | MAE: 119.60 kW
Running 4 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.8282 | MAE: 180.49 kW | MBE: -7.61 kW
Hourly R2 Score:   0.8419 | MAE: 170.00 kW
Daily R2 Score:    0.8555 | MAE: 125.98 kW
Running 5 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.8170 | MAE: 184.66 kW | MBE: -2.40 kW
Hourly R2 Score:   0.8306 | MAE: 174.14 kW
Daily R2 Score:    0.8369 | MAE: 131.23 kW
Running 6 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.8012 | MAE: 190.86 kW | MBE: 0.23 kW
Hourly R2 Score:   0.8147 | MAE: 180.16 kW
Daily R2 Score:    0.8131 | MAE: 137.30 kW
Running 7 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.7844 | MAE: 196.45 kW | MBE: 4.32 kW
Hourly R2 Score:   0.7978 | MAE: 185.91 kW
Daily R2 Score:    0.7856 | MAE: 143.78 kW
Running 8 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.7625 | MAE: 203.54 kW | MBE: 12.20 kW
Hourly R2 Score:   0.7760 | MAE: 192.85 kW
Daily R2 Score:    0.7543 | MAE: 149.06 kW
Running 9 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.7346 | MAE: 215.02 kW | MBE: 20.50 kW
Hourly R2 Score:   0.7480 | MAE: 205.19 kW
Daily R2 Score:    0.7140 | MAE: 164.70 kW
Running 10 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.7050 | MAE: 225.61 kW | MBE: 26.58 kW
Hourly R2 Score:   0.7181 | MAE: 216.31 kW
Daily R2 Score:    0.6697 | MAE: 177.70 kW
Running 11 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.6838 | MAE: 231.94 kW | MBE: 33.40 kW
Hourly R2 Score:   0.6967 | MAE: 222.48 kW
Daily R2 Score:    0.6343 | MAE: 181.29 kW
Running 12 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.6661 | MAE: 235.37 kW | MBE: 40.42 kW
Hourly R2 Score:   0.6788 | MAE: 225.91 kW
Daily R2 Score:    0.6002 | MAE: 185.33 kW
Running 13 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.6465 | MAE: 239.50 kW | MBE: 43.39 kW
Hourly R2 Score:   0.6587 | MAE: 229.71 kW
Daily R2 Score:    0.5643 | MAE: 188.08 kW
Running 14 day forecast
Loading consumption model from Models/con_model_feats_2f482541.json
5-Minute R2 Score: 0.6206 | MAE: 245.36 kW | MBE: 46.83 kW
Hourly R2 Score:   0.6325 | MAE: 235.46 kW
Daily R2 Score:    0.5200 | MAE: 193.38 kW

In [11]:
# Compare horizons.
forecast_scores = []

for name, preds in con_predictions.items():
    actual = deop_2022.loc[preds.index, "power-con-ave"]

    r2 = r2_score(actual, preds)
    mae = mean_absolute_error(actual, preds)

    forecast_scores.append({
        "forecast": name,
        "r2": r2,
        "mae": mae,
    })

forecast_scores = pd.DataFrame(forecast_scores)
forecast_scores

           forecast        r2         mae
0    1-Day Forecast  0.882619  152.804279
1    2-Day Forecast  0.862391  163.691902
2    3-Day Forecast  0.841419  174.637957
3    4-Day Forecast  0.828238  180.490175
4    5-Day Forecast  0.817009  184.664626
5    6-Day Forecast  0.801185  190.855143
6    7-Day Forecast  0.784353  196.447306
7    8-Day Forecast  0.762459  203.541874
8    9-Day Forecast  0.734574  215.015933
9   10-Day Forecast  0.704982  225.614677
10  11-Day Forecast  0.683759  231.942056
11  12-Day Forecast  0.666146  235.366796
12  13-Day Forecast  0.646516  239.503467
13  14-Day Forecast  0.620580  245.357448

In [12]:
# Plot feature importance.
importance_values = con_model.feature_importances_

feature_importance = pd.Series(
    importance_values,
    index=con_features,
).sort_values()

fig = px.bar(
    x=feature_importance.values,
    y=feature_importance.index,
    orientation="h",
    title="Consumption Model Feature Importance",
    labels={"x": "Importance", "y": "Feature"},
)

fig.show()